### PR TITLE
Validate form

### PR DESCRIPTION
**Pull request by mukhammadrizooff**
# Portfolio: validate contact form

**I made a simple confirmation in this branch:**

- I added that the content of the e-mail field should be written in lower case.

**I also did the following interactions:**

- When the user submitted the form, I checked that the email was written in lower case.
- If the inspection is good, the form will be sent.
- If the verification is not OK, you will see an error message next to the send button informing the user about the error and the form will not be sent.

### CODE REVIEW

**Comment by mukhammadrizooff** [comment]
**It was very fun 👍**

**Review by enaburekhan — CHANGES_REQUESTED** [review]
Hi Mukhammadrizooff, 

Good job so far!

- [x] Major highlights

- The PR summary and commit messages are very descriptive
- The readme is also very descriptive.

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [x] As part of the project requirements, the HTML/CSS linters should be set correctly in the project repository. I will recommend you add the `webhint` and `stylint` configuration to your app.  You can use this [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to get them.

I had to put this comment here because these config files are not present in the project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by mukhammadrizooff** [comment]
@enaburekhan Thak you for your suggestions and requirments.

**Review by rotimiazeez — APPROVED** [review]
# Hi Team, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mukhammadrizooff** [comment]
@rotimiazeez  Thank you.

**Pull request merged**
